services:
    caxy_app.answer_form_handler:
        class: caxy\AppBundle\Form\Handler\AnswerFormHandler
        arguments:
            - "@caxy_app.answer_manager"

    caxy_app.answer_manager:
        class: caxy\AppBundle\Service\AnswerManager
        arguments:
            - "@doctrine.orm.entity_manager"
